update

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,7 +1,9 @@
 #!/usr/bin/env bash
 echo "-----> Building React app..."
 cd $1/frontend
-#if npm run build; then
+npm run build
+if test $? -ne 0; then
+    echo "-----> Error building React app..."
     exit 1
-#fi
+fi
 echo "-----> React app build completed."
