update

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,9 +1,20 @@
 #!/usr/bin/env bash
 echo "-----> Building React app..."
+
 cd $1/frontend
-npm run build
+
+echo "-----> Installing packages..."
+npm install
 if test $? -ne 0; then
-    echo "-----> Error building React app..."
+    echo "-----> Error installing packages..."
     exit 1
 fi
+
+echo "-----> Building production files..."
+npm run build
+if test $? -ne 0; then
+    echo "-----> Error building production files app..."
+    exit 1
+fi
+
 echo "-----> React app build completed."
